language:
  - swift
osx_image: xcode10.1
script:
  - set -o pipefail
  - xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_PROJECT" -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' -enableCodeCoverage YES | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)