# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
#source 'https://dylankuang@itproject.earlylight.com.hk/bitbucket/scm/cl/elprogresshud.git'
target 'MBProgressHUDSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MBProgressHUDSwift
#  pod 'MBProgressHUD'
    pod 'ELProgressHUD'

end
